const nepalLocations = {
  Koshi: {
    districts: [
      "Bhojpur",
      "Dhankuta",
      "Ilam",
      "Jhapa",
      "Khotang",
      "Morang",
      "Okhaldhunga",
      "Panchthar",
      "Sankhuwasabha",
      "Solukhumbu",
      "Sunsari",
      "Taplejung",
      "Terhathum",
      "Udayapur",
    ],
  },
  Madhesh: {
    districts: [
      "Bara",
      "Parsa",
      "Rautahat",
      "Sarlahi",
      "Dhanusha",
      "Mahottari",
      "Saptari",
      "Siraha",
    ],
  },
  Bagmati: {
    districts: [
      "Bhaktapur",
      "Chitwan",
      "Dhading",
      "Dolakha",
      "Kathmandu",
      "Kavrepalanchok",
      "Lalitpur",
      "Makwanpur",
      "Nuwakot",
      "Ramechhap",
      "Rasuwa",
      "Sindhuli",
      "Sindhupalchok",
    ],
  },
  Gandaki: {
    districts: [
      "Baglung",
      "Gorkha",
      "Kaski",
      "Lamjung",
      "Manang",
      "Mustang",
      "Myagdi",
      "Nawalpur",
      "Parbat",
      "Syangja",
      "Tanahun",
    ],
  },
  Lumbini: {
    districts: [
      "Arghakhanchi",
      "Banke",
      "Bardiya",
      "Dang",
      "Gulmi",
      "Kapilvastu",
      "Palpa",
      "Parasi",
      "Pyuthan",
      "Rolpa",
      "Rukum East",
      "Rupandehi",
    ],
  },
  Karnali: {
    districts: [
      "Dailekh",
      "Dolpa",
      "Humla",
      "Jajarkot",
      "Jumla",
      "Kalikot",
      "Mugu",
      "Salyan",
      "Surkhet",
      "Rukum West",
    ],
  },
  Sudurpashchim: {
    districts: [
      "Achham",
      "Baitadi",
      "Bajhang",
      "Bajura",
      "Dadeldhura",
      "Darchula",
      "Doti",
      "Kailali",
      "Kanchanpur",
    ],
  },
};

// Major municipalities (you can expand this)
const majorMunicipalities = {
  Kathmandu: [
    { name: "Kathmandu Metropolitan City", type: "Metropolitan", wards: 32 },
    { name: "Budhanilkantha Municipality", type: "Municipality", wards: 13 },
    { name: "Chandragiri Municipality", type: "Municipality", wards: 15 },
    { name: "Dakshinkali Municipality", type: "Municipality", wards: 9 },
    { name: "Gokarneshwor Municipality", type: "Municipality", wards: 9 },
    {
      name: "Kageshwori Manohara Municipality",
      type: "Municipality",
      wards: 9,
    },
    { name: "Kirtipur Municipality", type: "Municipality", wards: 10 },
    { name: "Nagarjun Municipality", type: "Municipality", wards: 10 },
    { name: "Shankharapur Municipality", type: "Municipality", wards: 9 },
    { name: "Tarakeshwar Municipality", type: "Municipality", wards: 11 },
    { name: "Tokha Municipality", type: "Municipality", wards: 11 },
  ],
  Lalitpur: [
    { name: "Lalitpur Metropolitan City", type: "Metropolitan", wards: 29 },
    { name: "Godawari Municipality", type: "Municipality", wards: 14 },
    { name: "Mahalaxmi Municipality", type: "Municipality", wards: 10 },
  ],
  Bhaktapur: [
    { name: "Bhaktapur Municipality", type: "Municipality", wards: 10 },
    { name: "Changunarayan Municipality", type: "Municipality", wards: 9 },
    { name: "Madhyapur Thimi Municipality", type: "Municipality", wards: 9 },
    { name: "Suryabinayak Municipality", type: "Municipality", wards: 10 },
  ],
  // Add more districts and their municipalities as needed
};

module.exports = { nepalLocations, majorMunicipalities };
